//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2026 The Accelerator Fabric Scheduler Authors.
// All rights reserved.

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorDevice) DeepCopyInto(out *AcceleratorDevice) {
	*out = *in
	if in.NUMANode != nil {
		in, out := &in.NUMANode, &out.NUMANode
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorDevice.
func (in *AcceleratorDevice) DeepCopy() *AcceleratorDevice {
	if in == nil {
		return nil
	}
	out := new(AcceleratorDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorLink) DeepCopyInto(out *AcceleratorLink) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorLink.
func (in *AcceleratorLink) DeepCopy() *AcceleratorLink {
	if in == nil {
		return nil
	}
	out := new(AcceleratorLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorPlacementPolicy) DeepCopyInto(out *AcceleratorPlacementPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorPlacementPolicy.
func (in *AcceleratorPlacementPolicy) DeepCopy() *AcceleratorPlacementPolicy {
	if in == nil {
		return nil
	}
	out := new(AcceleratorPlacementPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorPlacementPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorPlacementPolicyList) DeepCopyInto(out *AcceleratorPlacementPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcceleratorPlacementPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorPlacementPolicyList.
func (in *AcceleratorPlacementPolicyList) DeepCopy() *AcceleratorPlacementPolicyList {
	if in == nil {
		return nil
	}
	out := new(AcceleratorPlacementPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorPlacementPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorPlacementPolicySpec) DeepCopyInto(out *AcceleratorPlacementPolicySpec) {
	*out = *in
	if in.Products != nil {
		in, out := &in.Products, &out.Products
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Weights = in.Weights
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorPlacementPolicySpec.
func (in *AcceleratorPlacementPolicySpec) DeepCopy() *AcceleratorPlacementPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AcceleratorPlacementPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorTopology) DeepCopyInto(out *AcceleratorTopology) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorTopology.
func (in *AcceleratorTopology) DeepCopy() *AcceleratorTopology {
	if in == nil {
		return nil
	}
	out := new(AcceleratorTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorTopology) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorTopologyList) DeepCopyInto(out *AcceleratorTopologyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcceleratorTopology, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorTopologyList.
func (in *AcceleratorTopologyList) DeepCopy() *AcceleratorTopologyList {
	if in == nil {
		return nil
	}
	out := new(AcceleratorTopologyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorTopologyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorTopologySpec) DeepCopyInto(out *AcceleratorTopologySpec) {
	*out = *in
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]AcceleratorDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Links != nil {
		in, out := &in.Links, &out.Links
		*out = make([]AcceleratorLink, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorTopologySpec.
func (in *AcceleratorTopologySpec) DeepCopy() *AcceleratorTopologySpec {
	if in == nil {
		return nil
	}
	out := new(AcceleratorTopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorTopologyStatus) DeepCopyInto(out *AcceleratorTopologyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastHeartbeatTime != nil {
		in, out := &in.LastHeartbeatTime, &out.LastHeartbeatTime
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorTopologyStatus.
func (in *AcceleratorTopologyStatus) DeepCopy() *AcceleratorTopologyStatus {
	if in == nil {
		return nil
	}
	out := new(AcceleratorTopologyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScoreWeights) DeepCopyInto(out *ScoreWeights) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScoreWeights.
func (in *ScoreWeights) DeepCopy() *ScoreWeights {
	if in == nil {
		return nil
	}
	out := new(ScoreWeights)
	in.DeepCopyInto(out)
	return out
}
